### ISSUE TITLE
Jupyter notebook with QuiverTools on CoCalc?

### ISSUE THREAD

**Issue by pbelmans** [QuiverTools/QuiverTools#25]
One interesting idea would be to make it possible for anyone to start a CoCalc instance with QuiverTools installed, so that they can interact with it from their browser.

Is this possible?

**Comment by giannipetrella** [comment]
CoCalc published notebooks [are not interactive](https://doc.cocalc.com/share.html#interactive-elements), unfortunately.

**Comment by pbelmans** [comment]
But it wouldn't be a published file; rather, it would create a new project with QuiverTools pre-installed.

Also, it doesn't have to be CoCalc per se. I'm inspired by mybinder, but that seems to be dysfunctional now?

**Comment by giannipetrella** [comment]
Creating a new project each time would incur a license problem: CoCalc projects without a license (i.e., free) do not have internet access, so a user could not install QuiverTools by cloning our repo. The only way to get QuiverTools running on a CoCalc project is to manually upload the files in ``quiver/`` to CoCalc...

It is also not possible to make an entire CoCalc project public, according to [CoCalc documentation](https://doc.cocalc.com/share.html#publishing-the-whole-project)...

On the other hand, mybinder seems to work for me but does not allow sage kernels by default. Maybe cloning [this repo](https://github.com/sagemath/sage-binder-env) in the QuiverTools organization and putting notebooks there could be a solution.

**Comment by pbelmans** [comment]
So that I don't forget: you can `pip install` from _within_ Sage by running

`%pip install git+https://github.com/QuiverTools/QuiverTools.git`

because I failed to run `sage --pip install git+https://github.com/QuiverTools/QuiverTools.git` in a Dockerfile. So running this within a notebook should install QuiverTools with a plain Sage!

**Comment by pbelmans** [comment]
Of course, I have absolutely no idea to actually interact with `.ipynb` files, this technology is too modern for me. Is this something that you can do, @giannipetrella? I've given the installation method, which hopefully works.

**Comment by pbelmans** [comment]
I'm abusing this issue like a chatbox, but, it now works!

I will do some cleanup, explain my workflow to create notebooks from actual Python files, and then we can at some point create a nice tutorial in mybinder.

**Comment by lnay** [comment]
GitHub Codespaces is another option, with free-tier users having a certain amount of free usage per month. The limitation though is the size of the devcontainers that they allow. SageMath is a large installation but the julia library has a good chance of being completely fine.

**Comment by lnay** [comment]
> So that I don't forget: you can `pip install` from _within_ Sage by running
> 
> `%pip install git+https://github.com/QuiverTools/QuiverTools.git`
> 
> because I failed to run `sage --pip install git+https://github.com/QuiverTools/QuiverTools.git` in a Dockerfile. So running this within a notebook should install QuiverTools with a plain Sage!

I imagine that operation requires git, which your container may not have? Alternatively, the raw contents could be downloaded without git and then `sage --pip install <directory>` with the correct setup.

**Comment by lnay** [comment]
If a container can be built within the size limitations, GitHub can also be used to host container images so they can be built ahead of time.
